// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXeJZ1YWHDErPUxaJe_wraArCHayXLPM',
    appId: '1:637492759790:android:67d98821dcc0fa37e677ff',
    messagingSenderId: '637492759790',
    projectId: 'settle-loans-14fc6',
    storageBucket: 'settle-loans-14fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUM-rn4qz76VL-d9qtLuPtTHnIjEZh2k',
    appId: '1:637492759790:ios:a32d0b302b9d5994e677ff',
    messagingSenderId: '637492759790',
    projectId: 'settle-loans-14fc6',
    storageBucket: 'settle-loans-14fc6.appspot.com',
    androidClientId: '637492759790-5kiusghfsh5orvpv5qlv9a34496593id.apps.googleusercontent.com',
    iosClientId: '637492759790-36qa03509sfp5tr65mlvj2v9au3ds039.apps.googleusercontent.com',
    iosBundleId: 'com.example.settleLoans',
  );
}
